In [4]:
import pandas as pd


In [4]:
obj=pd.Series([4,7,-5,3])
obj



0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2=pd.Series([4,7,-5,3],index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2["a"]

-5

In [13]:
obj2["d"]=6
obj2[["c","a","d"]]

c    3
a   -5
d    6
dtype: int64

In [14]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [15]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [3]:
import numpy as np
np.exp(obj2)

NameError: name 'obj2' is not defined

In [18]:
"b" in obj2


True

In [19]:
6 in obj2

False

In [21]:
sdata={"Ohio":35000,"Texas":71000,"Oregon":16000,"Utah":5000}
obj3=pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [24]:
states=["California","Ohio","Oregon","Texas"]
obj4=pd.Series(sdata,index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [27]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [29]:
obj3


Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [30]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [31]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [32]:
obj4.name="population"
obj4.index.name="state"
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [33]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [34]:
obj.index=["Bob","Steve","Jeff","Ryan"]
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [9]:
#DataFrame
data={"state":["Ohio","Ohio","Ohio","Nevada","Nevada","Nevada"],
     "year":[2000,2001,2002,2001,2002,2003],
     "pop":[1.5,1.7,3.6,2.4,2.9,3.2]}
frame=pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [37]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [38]:
pd.DataFrame(data,columns=["year","state","pop"])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [10]:
frame2=pd.DataFrame(data,columns=["year","state","pop","debt"],index=["one","two","three","four","five","six"])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [40]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [41]:
frame2["state"]

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [42]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [43]:
frame2.loc["three"]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [44]:
frame2["debt"]=16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [45]:
frame2["debt"]=np.arange(6)
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [46]:
va1=pd.Series([-1.2,-1.5,-1.7],index=["two","four","five"])
frame2["debt"]=va1
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [51]:
frame2["eastern"]=frame2.state=="Ohio"
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [52]:
del frame2["eastern"]
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [5]:
pop={"Nevada":{2001:2.4,2002:2.9},"Ohio":{2000:1.5,2001:1.7,2002:3.6}}
frame3=pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [54]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [31]:
pd.DataFrame(pop,columns=["Nevada","Ohio"],index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [58]:
pdata={"Ohio":frame3["Ohio"][:-1],"Nevada":frame3["Nevada"][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [6]:
frame3.index.name= "year"
frame3.columns.name="state"
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [7]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [11]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [14]:
obj=pd.Series(range(3),index=["a","b","c"])
index=obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [15]:
index[1:]

Index(['b', 'c'], dtype='object')

In [16]:
labels=pd.Index(np.arange(3))
labels


Int64Index([0, 1, 2], dtype='int64')

In [19]:
obj2=pd.Series([1.5,-2.5,0],index=labels)
obj2
obj2.index is labels

True

In [21]:
frame3
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [23]:
"Ohio" in frame3.columns

True

In [24]:
2003 in frame3.index

False

In [25]:
dup_labels=pd.Index(["foo","foo","bar","bar"])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [26]:
#5.2 功能
obj=pd.Series([4.5,7.2,-5.3,3.6],index=["d","b","a","c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [28]:
#使用reindex将索引重排，如果索引值不存在，引入缺失值
obj2=obj.reindex(['a',"b","c","d","e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [29]:
obj3=pd.Series(["blue","purple","yellow"],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [30]:
#在重新索引中有可能有缺失值，使用method中ffill可向前填充
obj3.reindex(range(6),method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [33]:
frame=pd.DataFrame(np.arange(9).reshape((3,3)),index=["a","c","d"],columns=["Ohio","Texas","California"])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [34]:
frame2=frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [35]:
states=["Texas","Utah","California"]
frame.reindex(columns=states)


Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [38]:
#丢弃指定轴上的项
obj=pd.Series(np.arange(5.),index=['a',"b","c","d","e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [39]:
new_obj=obj.drop("c")
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [40]:
obj.drop(["d","c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [41]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),index=["Ohio","Colorado","Utah","New York"],columns=["one","two","three","four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [43]:
data.drop(["Colorado","Ohio"])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [44]:
data.drop("two",axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [45]:
data.drop(["two","four"],axis="columns")

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [48]:
#inplace会销毁所有数据
obj=pd.Series(np.arange(5.),index=['a',"b","c","d","e"])
obj.drop("c",inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [49]:
#索引，选取，过滤
#索引
obj=pd.Series(np.arange(4),index=["a","b","c","d"])
obj

a    0
b    1
c    2
d    3
dtype: int32

In [50]:
obj["b"]

1

In [51]:
obj[1]

1

In [52]:
obj[2:4]

c    2
d    3
dtype: int32

In [53]:
obj[["b","a","d"]]

b    1
a    0
d    3
dtype: int32

In [54]:
obj[[1,3]]

b    1
d    3
dtype: int32

In [55]:
obj[obj<2]

a    0
b    1
dtype: int32

In [56]:
#使用标签的切片包含末端
obj["b":"c"]

b    1
c    2
dtype: int32

In [58]:
obj["b":"c"]=5
obj

a    0
b    5
c    5
d    3
dtype: int32

In [60]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),index=["Ohio","Colorado","Utah","New York"],columns=["one","two","three","four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [62]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [63]:
data[["three","one"]]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [64]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [65]:
data[data["three"]>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [66]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [68]:
data[data<5]=0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [69]:
#使用标签对行进行索取
data.loc["Colorado",["two","three"]]

two      5
three    6
Name: Colorado, dtype: int32

In [70]:
#使用整数对行进行索取
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [71]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [72]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [73]:
data.loc[:"Utah","two"]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [74]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [77]:
ser=pd.Series(np.arange(3))
ser
ser[-1]#pandas中不可以使用负数做出索引

KeyError: -1

In [78]:
ser2=pd.Series(np.arange(3.),index=["a","b","c"])
ser2[-1]

2.0

In [79]:
ser[:1]

0    0
dtype: int32

In [80]:
ser.loc[:1]

0    0
1    1
dtype: int32

In [81]:
ser.iloc[:1]

0    0
dtype: int32

In [82]:
#算术运算和数据对齐
s1=pd.Series ([7.3,-2.5,3.4,1.5],index=["a","c","d","e"])
s2=pd.Series([-2.1,3.6,-1.5,4,3.1],index=["a","c","e","f","g"])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [83]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [84]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [85]:
df1=pd.DataFrame(np.arange(9).reshape((3,3)),columns=list("bcd"),index=["Ohio","Texas","Colorado"])
df2=pd.DataFrame(np.arange(12).reshape((4,3)),columns=list("bde"),index=["Utah","Ohio","Texas","Oregon"])
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [86]:
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [87]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [88]:
df1=pd.DataFrame({"A":[1,2]})
df2=pd.DataFrame({"B":[3,4]})
df1

A
0  1
1  2

In [89]:
df2

B
0  3
1  4

In [90]:
df1-df2
#在DataFrame中如果没有共用的列或者行标签，结果都是空

A   B
0 NaN NaN
1 NaN NaN

In [93]:
#填充值
df1=pd.DataFrame(np.arange(12).reshape((3,4)),columns=list("abcd"))
df2=pd.DataFrame(np.arange(20).reshape(4,5),columns=list("abcde"))
df2
df2.loc[1,"b"]=np.nan
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [94]:
df2

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [95]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [96]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [97]:
1/df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [98]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [99]:
df1.reindex(columns=df2.columns,fill_value=0)

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

In [100]:
#dataframe 与series之间的运算
arr=np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
arr[0]

array([0, 1, 2, 3])

In [102]:
arr-arr[0]#broadcasting

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [105]:
frame=pd.DataFrame(np.arange(12).reshape((4,3)),columns=list("bde"),index=["Utah","Ohio","Texas","Oregon"])
frame
series=frame.iloc[0]
series

b    0
d    1
e    2
Name: Utah, dtype: int32

In [106]:
frame-series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [108]:

series2=pd.Series(range(3),index=["b","e","f"])
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [109]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [111]:
series3=frame["d"]
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int32

In [113]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [114]:
frame.sub(series,axis="index")

b   d   e
Ohio   NaN NaN NaN
Oregon NaN NaN NaN
Texas  NaN NaN NaN
Utah   NaN NaN NaN
b      NaN NaN NaN
d      NaN NaN NaN
e      NaN NaN NaN

In [116]:
#函数应用和映射
frame=pd.DataFrame(np.random.randn(4,3),columns=list("bde"),index=["Utah","Ohio","Texas","Oregon"])
frame

b         d         e
Utah   -0.681491  0.695487  0.078078
Ohio    0.935268  0.315952 -0.448408
Texas  -0.168426  0.776916 -0.858817
Oregon  0.028422  0.619224 -2.127424

In [117]:
np.abs(frame)

b         d         e
Utah    0.681491  0.695487  0.078078
Ohio    0.935268  0.315952  0.448408
Texas   0.168426  0.776916  0.858817
Oregon  0.028422  0.619224  2.127424

In [118]:
f=lambda x:x.max()-x.min()
frame.apply(f)
#使用此功能按列

b    1.616759
d    0.460964
e    2.205502
dtype: float64

In [119]:
frame.apply(f,axis="columns")
#原来默认是列，使用axis=columns 则会使用行

Utah      1.376978
Ohio      1.383676
Texas     1.635733
Oregon    2.746648
dtype: float64

In [120]:
def f(x):
    return pd.Series([x.min(),x.max()],index=["min","max"])
frame.apply(f)

b         d         e
min -0.681491  0.315952 -2.127424
max  0.935268  0.776916  0.078078

In [121]:
format=lambda x:"%.2f"%x#保留小数点后2位
frame.applymap(format)

b     d      e
Utah    -0.68  0.70   0.08
Ohio     0.94  0.32  -0.45
Texas   -0.17  0.78  -0.86
Oregon   0.03  0.62  -2.13

In [122]:
frame["e"].map(format)

Utah       0.08
Ohio      -0.45
Texas     -0.86
Oregon    -2.13
Name: e, dtype: object

In [123]:
#排序和排名
obj=pd.Series(range(4),index=["d","a","b","c"])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [134]:
frame=pd.DataFrame(np.arange(8).reshape((2,4)),index=["three","one"],columns=["d","a","b","c"])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [135]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [136]:
frame.sort_index(axis=1,ascending=False)
#按照列的降序排列

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [137]:
obj=pd.Series([4,7,-3,2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [138]:
#缺失值在series的末尾
obj=pd.Series([4,np.nan,7,np.nan,-3,2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [139]:
frame=pd.DataFrame({"b":[4,7,-3,2],"a":[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [141]:
#by可以选择使用哪一列或者行来排序
frame.sort_values(by="b")

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [142]:
frame.sort_values(by=["a","b"])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [143]:
#rankrank 表示在这个数在原来的Series中排第几名，有相同的数，取其排名平均（默认）作为值。
obj=pd.Series([7,-5,7,4,2,0,4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [144]:
#method表示按出现的顺序做出排名
obj.rank(method="first")

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [145]:
obj.rank(ascending=False,method="max")

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [146]:
frame=pd.DataFrame({"b":[4.3,7,-3,2],"a":[0,1,0,1],"c":[-2,5,8,-2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [147]:
frame.rank(axis="columns")

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [148]:
#重复标签的轴索引
obj=pd.Series(range(5),index=["a","a","b","b","c"])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [149]:
obj.index.is_unique

False

In [150]:
obj["a"]

a    0
a    1
dtype: int64

In [151]:
obj["c"]

4

In [152]:
df=pd.DataFrame(np.random.randn(4,3),index=["a","a","b","b"])
df


0         1         2
a  1.636086 -2.013373  0.596010
a -1.155613 -0.350106 -1.428201
b  0.386955  0.076927  1.273455
b  0.029555  1.283127 -1.016239

In [153]:
df.loc["b"]

0         1         2
b  0.386955  0.076927  1.273455
b  0.029555  1.283127 -1.016239

In [155]:
#5.3汇总和计算描述统计
df=pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=["a","b","c","d"],columns=["one","two"])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [156]:
#sum返回的是按列的和
df.sum()

one    9.25
two   -5.80
dtype: float64

In [157]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [158]:
df.mean(axis="columns",skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [159]:
df.idxmax()#idmax返回得失最大值或者最小值的索引

one    b
two    d
dtype: object

In [160]:
df.cumsum()#计算的是按列的累计值

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [162]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [163]:
obj=pd.Series(["a","a","b","c"]*4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [164]:
conda install pandas-datareader

SyntaxError: invalid syntax (<ipython-input-164-990bbb6ee910>, line 1)

In [165]:
import pandas_datareader.data as web


ModuleNotFoundError: No module named 'pandas_datareader'

In [7]:
import pandas as pd
import pickle
price=pd.read_pickle("yahoo_price.pkl")
volume=pd.read_pickle("yahoo_volume.pkl")
price


AAPL        GOOG         IBM       MSFT
Date                                                     
2010-01-04   27.990226  313.062468  113.304536  25.884104
2010-01-05   28.038618  311.683844  111.935822  25.892466
2010-01-06   27.592626  303.826685  111.208683  25.733566
2010-01-07   27.541619  296.753749  110.823732  25.465944
2010-01-08   27.724725  300.709808  111.935822  25.641571
2010-01-11   27.480148  300.255255  110.763844  25.315406
2010-01-12   27.167562  294.945572  111.644958  25.148142
2010-01-13   27.550775  293.252243  111.405433  25.382312
2010-01-14   27.391211  294.630868  113.184773  25.892466
2010-01-15   26.933449  289.710772  112.731385  25.808835
2010-01-19   28.124939  293.516976  114.750251  26.009552
2010-01-20   27.692027  289.915587  111.422546  25.583028
2010-01-21   27.213337  291.199286  110.353231  25.097963
2010-01-22   25.863592  274.730736  107.359151  24.219826
2010-01-25   26.559391  269.730740  107.889534  24.520902
2010-01-26   26.934757  270.939526  107.573014  24.671439
2010-01-27   27.188489  270.779695  108.069178  24.813614
2010-01-28   26.065007  266.878565  105.862111  24.387091
2010-01-29   25.119401  264.705742  104.698697  23.567497
2010-02-01   25.468608  266.244198  106.649125  23.759851
2010-02-02   25.616400  265.295156  107.384814  23.801666
2010-02-03   26.057159  270.140309  107.496027  23.943840
2010-02-04   25.118093  263.127321  105.220523  23.283148
2010-02-05   25.564084  265.380075  105.665355  23.433686
2010-02-08   25.388826  266.468996  104.728745  23.182789
2010-02-09   25.659561  267.952522  105.871586  23.425323
2010-02-10   25.519617  266.958496  105.527873  23.408596
2010-02-11   25.983917  267.932539  106.318414  23.517319
2010-02-12   26.207567  266.294170  106.550416  23.358417
2010-02-16   26.602551  270.380071  107.607330  23.820544
...                ...         ...         ...        ...
2016-09-12  105.440002  769.020020  158.289993  57.049999
2016-09-13  107.949997  759.690002  155.809998  56.529999
2016-09-14  111.769997  762.489990  154.050003  56.259998
2016-09-15  115.570000  771.760010  155.660004  57.189999
2016-09-16  114.919998  768.880005  153.839996  57.250000
2016-09-19  113.580002  765.700012  154.869995  56.930000
2016-09-20  113.570000  771.409973  154.449997  56.810001
2016-09-21  113.550003  776.219971  155.529999  57.759998
2016-09-22  114.620003  787.210022  156.110001  57.820000
2016-09-23  112.709999  786.900024  154.979996  57.430000
2016-09-26  112.879997  774.210022  153.979996  56.900002
2016-09-27  113.089996  783.010010  156.770004  57.950001
2016-09-28  113.949997  781.559998  158.289993  58.029999
2016-09-29  112.180000  775.010010  158.110001  57.400002
2016-09-30  113.050003  777.289978  158.850006  57.599998
2016-10-03  112.519997  772.559998  157.610001  57.419998
2016-10-04  113.000000  776.429993  156.460007  57.240002
2016-10-05  113.050003  776.469971  157.080002  57.639999
2016-10-06  113.889999  776.859985  156.880005  57.740002
2016-10-07  114.059998  775.080017  155.669998  57.799999
2016-10-10  116.050003  785.940002  157.020004  58.040001
2016-10-11  116.300003  783.070007  154.789993  57.189999
2016-10-12  117.339996  786.140015  154.289993  57.110001
2016-10-13  116.980003  778.190002  153.720001  56.919998
2016-10-14  117.629997  778.530029  154.449997  57.419998
2016-10-17  117.550003  779.960022  154.770004  57.220001
2016-10-18  117.470001  795.260010  150.720001  57.660000
2016-10-19  117.120003  801.500000  151.259995  57.529999
2016-10-20  117.059998  796.969971  151.520004  57.250000
2016-10-21  116.599998  799.369995  149.630005  59.660000

[1714 rows x 4 columns]

In [8]:
volume


AAPL      GOOG       IBM       MSFT
Date                                                
2010-01-04  123432400   3927000   6155300   38409100
2010-01-05  150476200   6031900   6841400   49749600
2010-01-06  138040000   7987100   5605300   58182400
2010-01-07  119282800  12876600   5840600   50559700
2010-01-08  111902700   9483900   4197200   51197400
2010-01-11  115557400  14479800   5730400   68754700
2010-01-12  148614900   9742900   8081500   65912100
2010-01-13  151473000  13041800   6455400   51863500
2010-01-14  108223500   8511900   7111800   63228100
2010-01-15  148516900  10909600   8494400   79913200
2010-01-19  182501900   8665700  13916200   46575700
2010-01-20  153038200   6525700  15197500   54849500
2010-01-21  152038600  12662600   9608600   73086700
2010-01-22  220441900  13651700  10088600  102004600
2010-01-25  266424900   8872800   5738500   63373000
2010-01-26  466777500   8743600   7135300   66639900
2010-01-27  430642100   7958400   8719200   63949500
2010-01-28  293375600   6482300   9622200  117513700
2010-01-29  311488100   8311900  11571200  193888500
2010-02-01  187469100   4518400   7242900   85931100
2010-02-02  174585600   8223000   5899900   54413700
2010-02-03  153832000   6020500   4177100   61397900
2010-02-04  189413000   6780600   9126900   77850000
2010-02-05  212576700   6335600   8617000   80960100
2010-02-08  119567700   5408700   5718500   52820600
2010-02-09  158221700   5660200   6044500   59195800
2010-02-10   92590400   5369000   5219100   48591300
2010-02-11  137586400   4838000   5089000   65993700
2010-02-12  163867200   4576400   8017700   81117200
2010-02-16  135934400   7336100   6777300   51935600
...               ...       ...       ...        ...
2016-09-12   45292800   1286800   4367500   29303000
2016-09-13   62176200   1379900   3636700   30130200
2016-09-14  110888700   1087400   3860600   24062500
2016-09-15   89983600   1305100   3645600   26847000
2016-09-16   79886900   2046000   6463600   44607000
2016-09-19   47023000   1171100   2450100   20937100
2016-09-20   34514300    975300   2159100   17384000
2016-09-21   36003200   1151400   2473900   33707300
2016-09-22   31074000   1463600   2691100   19822200
2016-09-23   52481200   1409500   2702200   19955300
2016-09-26   29869400   1508500   2533300   21688700
2016-09-27   24607400   1138800   2987200   28065100
2016-09-28   29641100   1107900   3310000   20536400
2016-09-29   35887000   1301400   3374800   25463500
2016-09-30   36379100   1580300   3596900   29910800
2016-10-03   21701800   1275900   2227800   19189500
2016-10-04   29736800   1197400   2884100   20085900
2016-10-05   21453100   1457100   1684500   16726400
2016-10-06   28779300   1066300   1950100   16212600
2016-10-07   24358400    930700   2671900   20089000
2016-10-10   36236000   1161400   2481300   18196500
2016-10-11   64041000   1368000   2901300   26497400
2016-10-12   37586800    934900   2964000   22177500
2016-10-13   35192400   1300400   2909900   25313700
2016-10-14   35652200    851100   4358200   27402500
2016-10-17   23624900   1089500   5890400   23830000
2016-10-18   24553500   1995600  12770600   19149500
2016-10-19   20034600    116600   4632900   22878400
2016-10-20   24125800   1734200   4023100   49455600
2016-10-21   22384800   1260500   4401900   79974200

[1714 rows x 4 columns]

In [9]:
returns=price.pct_change()
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [11]:
#计算 msft与ibm的相关系数
returns["MSFT"].corr(returns["IBM"])


0.4997636114415114

In [12]:
#计算协方差
returns["MSFT"].cov(returns["IBM"])

8.870655479703546e-05

In [14]:
returns.MSFT.corr(returns.IBM)

0.4997636114415114

In [15]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [16]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

In [17]:
#这一列或者这一行与其他series之间的关系
returns.corrwith(returns.IBM)

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [18]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

In [19]:
#唯一值，值计数以及成员资格
obj=pd.Series(["c","a","d","a","a","b","b","c","c"])

In [20]:
uniques=obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [21]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [22]:
pd.value_counts(obj.values,sort=False)

d    1
c    3
a    3
b    2
dtype: int64

In [23]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [24]:
mask=obj.isin(["b","c"])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [25]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [27]:
to_match=pd.Series(["c","a","b","b","c","a"])
unique_vals=pd.Series(["c","b","a"])
pd.Index(unique_vals).get_indexer(to_match)
#Index.get_index 的用法是 unique_vals中的数组匹配计算到to_match中去

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [28]:
data=pd.DataFrame({"Qu1":[1,3,4,3,4],"Qu2":[2,3,1,2,3],"Qu3":[1,5,2,4,4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [30]:

result=data.apply(pd.value_counts).fillna(0)
result
#pd.value_counts 行标签是将列中的值都展示出来，后面的值则是每一列中这个值的计数

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0