In [2]:
#chapter 7 数据清洗和准备工作
#7.1 缺失数据处理
import pandas as pd
import numpy as np

In [5]:
string_data=pd.Series(["aardvark","artichoke",np.nan,"avocado"])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [6]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [7]:
string_data[0]=None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [8]:
#z过滤缺失数据
from numpy import nan as NA
data=pd.Series([1,NA,3.5,NA,7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [9]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [12]:
data=pd.DataFrame([[1,6.5,3],[1,NA,NA],[NA,NA,NA],[NA,6.5,3]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [13]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [14]:
#传入how=all则丢球全部是NA的行
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [16]:
data[4]=NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [17]:
data.dropna(axis=1,how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [19]:
df=pd.DataFrame(np.random.randn(7,3))
df

0         1         2
0 -0.208846 -0.462335  0.230977
1 -0.390591 -1.245748 -0.524443
2 -0.148003  0.409179  0.186029
3  1.305186 -0.027493  0.488546
4  1.603056 -0.470078  0.230605
5 -1.377790 -0.768950  1.399641
6 -1.931560  0.541933 -0.766330

In [20]:
df.iloc[:4,1]=NA
df

0         1         2
0 -0.208846       NaN  0.230977
1 -0.390591       NaN -0.524443
2 -0.148003       NaN  0.186029
3  1.305186       NaN  0.488546
4  1.603056 -0.470078  0.230605
5 -1.377790 -0.768950  1.399641
6 -1.931560  0.541933 -0.766330

In [21]:
df.iloc[:2,2]=NA
df

0         1         2
0 -0.208846       NaN       NaN
1 -0.390591       NaN       NaN
2 -0.148003       NaN  0.186029
3  1.305186       NaN  0.488546
4  1.603056 -0.470078  0.230605
5 -1.377790 -0.768950  1.399641
6 -1.931560  0.541933 -0.766330

In [22]:
df.dropna()

0         1         2
4  1.603056 -0.470078  0.230605
5 -1.377790 -0.768950  1.399641
6 -1.931560  0.541933 -0.766330

In [33]:
#thresh可选项,指每一行留下多少个 有数据
df.iloc[:1,0]=NA
df.dropna(axis=1,how="all")
df.dropna(thresh=1)
df.dropna(axis=1,how="all")

0         1         2
0       NaN       NaN       NaN
1 -0.390591       NaN       NaN
2 -0.148003       NaN  0.186029
3  1.305186       NaN  0.488546
4  1.603056 -0.470078  0.230605
5 -1.377790 -0.768950  1.399641
6 -1.931560  0.541933 -0.766330

In [30]:
#填充数据
df.fillna(0)

0         1         2  (0, 0)
0  0.000000  0.000000  0.000000     0.0
1 -0.390591  0.000000  0.000000     0.0
2 -0.148003  0.000000  0.186029     0.0
3  1.305186  0.000000  0.488546     0.0
4  1.603056 -0.470078  0.230605     0.0
5 -1.377790 -0.768950  1.399641     0.0
6 -1.931560  0.541933 -0.766330     0.0

In [35]:
#通过字典调用fillna，实现对不同干的列填充不同的值
df.fillna({1:0.5,2:0})
df.fillna({(0,0):3})

0         1         2  (0, 0)
0       NaN       NaN       NaN     3.0
1 -0.390591       NaN       NaN     3.0
2 -0.148003       NaN  0.186029     3.0
3  1.305186       NaN  0.488546     3.0
4  1.603056 -0.470078  0.230605     3.0
5 -1.377790 -0.768950  1.399641     3.0
6 -1.931560  0.541933 -0.766330     3.0

In [38]:
df=df.fillna(0,inplace=True)
df

AttributeError: 'NoneType' object has no attribute 'fillna'

In [39]:
df=pd.DataFrame(np.random.randn(6,3))
df

0         1         2
0 -0.047372  0.724586 -0.335629
1 -0.599463  0.233328  0.711669
2  0.449263  0.998234  1.387826
3 -0.106787  1.296213 -1.259986
4  0.452234 -1.024310 -0.548661
5 -1.069323  0.295361  0.421005

In [40]:
df.iloc[2:,1]=NA
df

0         1         2
0 -0.047372  0.724586 -0.335629
1 -0.599463  0.233328  0.711669
2  0.449263       NaN  1.387826
3 -0.106787       NaN -1.259986
4  0.452234       NaN -0.548661
5 -1.069323       NaN  0.421005

In [41]:
df.iloc[4:,2]=NA
df

0         1         2
0 -0.047372  0.724586 -0.335629
1 -0.599463  0.233328  0.711669
2  0.449263       NaN  1.387826
3 -0.106787       NaN -1.259986
4  0.452234       NaN       NaN
5 -1.069323       NaN       NaN

In [42]:
df.fillna(method="ffill")

0         1         2
0 -0.047372  0.724586 -0.335629
1 -0.599463  0.233328  0.711669
2  0.449263  0.233328  1.387826
3 -0.106787  0.233328 -1.259986
4  0.452234  0.233328 -1.259986
5 -1.069323  0.233328 -1.259986

In [43]:
df.fillna(method="ffill",limit=2)

0         1         2
0 -0.047372  0.724586 -0.335629
1 -0.599463  0.233328  0.711669
2  0.449263  0.233328  1.387826
3 -0.106787  0.233328 -1.259986
4  0.452234       NaN -1.259986
5 -1.069323       NaN -1.259986

In [44]:
data=pd.Series([1,NA,3.5,NA,7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [46]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [48]:
#数据转换
data=pd.DataFrame({"k1":["one","two"]*3+["two"],"k2":[1,1,2,3,3,4,4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [49]:
#duplicated检查每行是否重复
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [50]:
#丢弃发现重复的行
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [51]:
data["v1"]=range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [52]:
#根据k1的值将重复项去掉
data.drop_duplicates(["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [53]:
data.drop_duplicates(["k1","k2"])


k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5

In [54]:
data.drop_duplicates(["k1","k2"],keep="last")
#last则意味着保留重复出现组合的最后一个

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [57]:
#利用函数或者映射进行数据转换
data=pd.DataFrame({"food":["bacon","pulled pork","bacon","Pastrami","corned beef","Bacon","Pastrami","honey ham","nova lox"],"ounces":[4,3,12,6,7.5,8,3,5,6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     Pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [78]:
meat_to_animal={"bacon":"pig","pulled pork":"pig","pastrami":"cow","corned beef":"cow","honey ham":"pig","nova lox":"salmon"}

In [79]:
#str.lower将字符换中的值转换为小写
lowercased=data["food"].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [80]:
data["animal"]=lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     Pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [81]:
data['food'].map(lambda x:meat_to_animal[x.lower()] )
#使用map接受一个函数或者映射关系的字典对象，实现元素集转换

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [85]:
#替换值
data=pd.Series([1.,-999,2,-999,-1000,3])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [86]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [87]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [88]:
data.replace({-999:np.nan,-1000:0})
#replace功能用在数字上

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [91]:
#重命名轴索引
data=pd.DataFrame(np.arange(12).reshape((3,4)),index=["Ohio","Colorado","New York"],columns=["one","two","three","four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [94]:
transform=lambda x:x[:4].upper()
data.index.map(transform)
#将轴索引前4个字母改成大写

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [95]:
data.index=data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [98]:
data.rename(index=str.title,columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [103]:
data.rename(index={"OHIO":"INDIANA"},columns={"three":"peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [104]:
#inplace意在不创建新的对象，对原有数据列进行修改
data.rename(index={"OHIO":"INDIANA"},inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [105]:
#将数据离散化和bin划分
ages=[20,22,25,27,21,23,37,31,61,45,41,32]
bins=[18,25,35,60,100]
cats=pd.cut(ages,bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [107]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [109]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [110]:
pd.value_counts(cats)
#pd.value_counts 是pandas。cut的结果的面元计数

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [111]:
pd.cut(ages,[18,26,36,61,100],right=False)
#right=false意味着右开

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [112]:
group_names=["Youth","YoungAdult","MiddleAged","Senior"]
pd.cut(ages,bins,labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [113]:
data=np.random.randn(20)
data

array([-0.09578576, -2.4314337 , -0.81733914, -0.08993418, -1.00216141,
       -0.00550628, -0.671835  ,  0.50748792,  0.65423897,  2.35525673,
        0.48955777, -1.28826216, -0.45839893,  1.06564633,  0.17750245,
       -0.96174121, -0.36882435,  0.07083798,  1.1229198 ,  1.05666634])

In [114]:
pd.cut(data,4,precision=2)
#precision 将小数点限定为2位

[(-1.23, -0.038], (-2.44, -1.23], (-1.23, -0.038], (-1.23, -0.038], (-1.23, -0.038], ..., (-1.23, -0.038], (-1.23, -0.038], (-0.038, 1.16], (-0.038, 1.16], (-0.038, 1.16]]
Length: 20
Categories (4, interval[float64]): [(-2.44, -1.23] < (-1.23, -0.038] < (-0.038, 1.16] < (1.16, 2.36]]

In [115]:
#qcut 可以使得每个面元拥有差不多的数量
data=np.random.randn(1000)
cats=pd.qcut(data,4)
cats

[(-0.687, -0.0045], (0.665, 2.896], (0.665, 2.896], (0.665, 2.896], (-0.0045, 0.665], ..., (0.665, 2.896], (-0.687, -0.0045], (-2.996, -0.687], (-0.687, -0.0045], (-0.687, -0.0045]]
Length: 1000
Categories (4, interval[float64]): [(-2.996, -0.687] < (-0.687, -0.0045] < (-0.0045, 0.665] < (0.665, 2.896]]

In [116]:
pd.value_counts(cats)

(0.665, 2.896]       250
(-0.0045, 0.665]     250
(-0.687, -0.0045]    250
(-2.996, -0.687]     250
dtype: int64

In [118]:
pd.qcut(data,[0,0.1,0.5,0.9,1])
?pd.qcut


In [119]:
#检测和过滤异常值
data=pd.DataFrame(np.random.randn(1000,4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.035299     0.029912     0.015367     0.035287
std       0.959057     1.000923     1.008267     0.983088
min      -2.702258    -3.000745    -2.841178    -3.027768
25%      -0.694831    -0.632286    -0.652263    -0.649133
50%      -0.025103    -0.002346    -0.029022     0.032416
75%       0.623239     0.706857     0.682271     0.671874
max       3.582829     2.736465     3.225988     3.133361

In [120]:
col=data[2]
col[np.abs(col)>3]

678    3.225988
Name: 2, dtype: float64

In [121]:
data[(np.abs(data)>3).any(1)]
#选出一行，这一行中有1个数字>3

0         1         2         3
7   -1.049737 -0.933226 -1.270999 -3.027768
259 -0.238659 -3.000745  0.705963 -1.262743
566  1.323854  2.348469  0.233138  3.133361
678 -0.484260  0.598695  3.225988 -2.071700
714  3.582829  0.515564 -0.512355 -1.694904

In [122]:
#将数据集中大于3的数据赋值3,0，-3
data[np.abs(data)>3]=np.sign(data)*3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.035882     0.029913     0.015141     0.035182
std       0.957031     1.000921     1.007572     0.982590
min      -2.702258    -3.000000    -2.841178    -3.000000
25%      -0.694831    -0.632286    -0.652263    -0.649133
50%      -0.025103    -0.002346    -0.029022     0.032416
75%       0.623239     0.706857     0.682271     0.671874
max       3.000000     2.736465     3.000000     3.000000

In [123]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0 -1.0  1.0  1.0
3 -1.0  1.0  1.0 -1.0
4  1.0 -1.0  1.0  1.0

In [124]:
#排列和随机采样
df=pd.DataFrame(np.arange(5*4).reshape((5,4)))
sampler=np.random.permutation(5)
sampler

array([1, 0, 3, 2, 4])

In [125]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [126]:
df.take(sampler)
#take将原有的df按新的smapler排序方法进行排序

0   1   2   3
1   4   5   6   7
0   0   1   2   3
3  12  13  14  15
2   8   9  10  11
4  16  17  18  19

In [127]:
df.sample(n=3)
#随机选取3行

0   1   2   3
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [128]:
choices=pd.Series([5,7,-1,6,4])
draws=choices.sample(n=10,replace=True)
draws
#随机选取10个choices中的数值，并代替旧的数组

0    5
2   -1
1    7
0    5
3    6
1    7
1    7
3    6
4    4
4    4
dtype: int64

In [129]:
#计算指标、哑变量
df=pd.DataFrame({"key":["b","b","a","c","a","b"],"data1":range(6)})
pd.get_dummies(df["key"])
#上述组合将key中的值使用0，1 表现出这一行表示哪个数据点

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [130]:
dummies=pd.get_dummies(df["key"],prefix="key")
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [131]:
df_with_dummy=df[["data1"]].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [133]:
mnames=["movie_id","title","genres"]
movies=pd.read_table("movies.dat",sep="::",header=None,names=mnames)
movies[:10]

D:\anaconda\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [137]:
all_genres=[]
for x in movies.genres:
    all_genres.extend(x.split("|"))
genres=pd.unique(all_genres)

In [138]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [ ]:
zero_matris=np.zeros((len(movies),len(genres)))
dummies=pd.DataFrame(zero_matrix.columns=genres)

In [139]:
gen=movies.genres[0]
gen.split("|")


['Animation', "Children's", 'Comedy']

In [140]:
dummies.columns.get_indexer(gen.split("|"))


array([-1, -1, -1], dtype=int64)

In [141]:
for i,gen in enumerate(movies.genres):
    indices=dummies.columns.get_indexer(gen.split("|"))
    dummies.iloc[i,indices]=1

IndexError: single positional indexer is out-of-bounds

In [142]:
movies_windic=movies.join(dummies.add_prefix("Genre_"))
movies_windic.iloc[0]

movie_id                                 1
title                     Toy Story (1995)
genres         Animation|Children's|Comedy
Genre_key_a                              0
Genre_key_b                              1
Genre_key_c                              1
Name: 0, dtype: object

In [143]:
np.random.seed(12345)
values=np.random.randn(10)
values

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057,
        1.39340583,  0.09290788,  0.28174615,  0.76902257,  1.24643474])

In [144]:
bins=[0,0.2,0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           0
1           0           0           1           0           0
2           0           0           0           0           0
3           0           0           0           0           0
4           0           0           0           0           0
5           0           0           0           0           0
6           1           0           0           0           0
7           0           1           0           0           0
8           0           0           0           1           0
9           0           0           0           0           0

In [145]:
#7.3 字符串
val="a,b,  guido"
val.split(",")

['a', 'b', '  guido']

In [146]:
pieces=[x.strip() for x in val.split(",")]
pieces

['a', 'b', 'guido']

In [147]:
first,second,third=pieces
first+"::"+second+"::"+third

'a::b::guido'

In [148]:
"::".join(pieces)

'a::b::guido'

In [149]:
"guido" in val

True

In [150]:
val.index(",")

1

In [151]:
val.find(":")
#find假设不是其中字符返回-1，但index则会返回报错

-1

In [152]:
val.count(",")

2

In [153]:
val.replace(",","::")

'a::b::  guido'

In [154]:
val.replace(",","")

'ab  guido'

In [155]:
#正则表达式
import re

In [157]:
text="foo     bar\t baz    \tqux"
re.split("\s+",text)
#使用|s+，text正则表达会被变异，再调用split

['foo', 'bar', 'baz', 'qux']

In [158]:
regex=re.compile("\s+")
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [159]:
regex.findall(text)

['     ', '\t ', '    \t']

In [160]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'


regex = re.compile(pattern, flags=re.IGNORECASE)

In [161]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [164]:
m=regex.search(text)
m
text[m.start():m.end()]

'dave@google.com'

In [165]:
print(regex.match(text))

None


In [166]:
print(regex.sub("REDACTED",text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [167]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern, flags=re.IGNORECASE)

In [168]:
m = regex.match('wesm@bright.net')

m.groups()


('wesm', 'bright', 'net')

In [169]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [171]:
data={"Dave":"dave@google.com","Steve":"steve@gmail.com","Rob":"rob@gmail.com","Wes":np.nan}
data=pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [172]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [173]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [174]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [175]:
data.str.findall(pattern,flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [176]:
matches=data.str.match(pattern,flags=re.IGNORECASE)
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [177]:
matches.str.get(1)

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [179]:
matches.str[0]

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [180]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object